name: Acceptance tests
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.go"
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
jobs:
  acceptance_tests:
    container:
      image: asomesan/ghworker
      volumes:
        - "/home/runner/.kube/config:/home/ghaction/.kube/config"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.10.0"
      - name: Run tests
        run: |
          make testacc KUBE_CONFIG_PATH="${HOME}/.kube/config" TF_ACC_LOG_PATH=$HOME/tftest.log
