name: Acceptance tests
on:
  push:
    branches:
      - master
      - main
    paths:
      - "**.go"
  pull_request:
    branches:
      - master
    paths:
      - "**.go"
jobs:
  acceptance_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: engineerd/setup-kind@v0.5.0
      - name: Run tests
        env:
          TF_ACC_TERRAFORM_VERSION: "0.14.10"
          TF_ACC_ACC_TEMP_DIR: ${{ runner.temp }}
        run: |
          make testacc KUBE_CONFIG_PATH="${HOME}/.kube/config" TF_ACC_LOG_PATH="${HOME}/tftest.log"
